DROP TABLE IF EXISTS FACULTY;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS CLUBS;
DROP TABLE IF EXISTS MEETINGS;

CREATE TABLE FACULTY (
    Faculty_ID INT PRIMARY KEY AUTO_INCREMENT,
    Faculty_Name VARCHAR(70) NOT NULL
)

CREATE TABLE STUDENT (
    Student_ID INT PRIMARY KEY AUTO_INCREMENT,
    Student_Name VARCHAR(70) NOT NULL
)

CREATE TABLE CLUBS (
    Club_Name VARCHAR(70) PRIMARY KEY,
    Faculty_ID INT,
    Annual_Expenses DECIMAL(10, 2),
    Annual_Budget DECIMAL(10, 2),

    CONSTRAINT FALCULTY_FK FOREIGN KEY (Faculty_ID) REFERENCES FACULTY(Faculty_ID)
)

CREATE TABLE MEETINGS (
    
)